application: pcmedkit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img

- url: /.*
  script: handle_main.app

- url: /admin.*
  script: handle_main.admin
  login: admin
  secure: always

- url: /post/(?P<site>).+/medkit
  script: handle_main.app

- url: /post/(?P<site>).+/medkit
  script: handle_main.siteadmin
  login: admin
  secure: always

- url: /.*
  script: handle_main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: django
  version: "1.5"
- name: jinja2
  version: "2.6"

builtins:
- remote_api: on
